Подключится к библиотеке NUMPY

In [2]:
import numpy as np

 Создайте массив из 10 нулей

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Создать массив из 10 единиц

In [3]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

Создать массив из 10 пятерок

In [ ]:
np.full(10,5)


array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

Создать массив из целых чисел от 10 до 50

In [5]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

Создать массив из четных чисел от 10 до 50

In [4]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

Создать матрицу 3х3 с числами от 0 до 8

In [ ]:
np.arange(9).reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.shape((3,3))

(2,)

Создать единичную матрицу 3x3

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

:Используйте NumPy для генерации случайного числа от 0 до 1
Используйте NumPy для генерации массива из 25 случайных чисел,взятых из стандартного нормального распределения

In [ ]:
arr=np.random.rand(5,5)
arr

array([[0.22089632, 0.17819231, 0.76970469, 0.52646468, 0.32916735],
       [0.15036613, 0.80930899, 0.51954644, 0.87408599, 0.89344282],
       [0.04562945, 0.04683136, 0.89660442, 0.15237843, 0.47076788],
       [0.43129255, 0.3269171 , 0.70904911, 0.70875204, 0.25288772],
       [0.11508632, 0.16783695, 0.43752517, 0.40014473, 0.23169184]])

 Используйте NumPy для генерации массива из 25 случайных чисел, взятых из стандартного нормального распределения

In [ ]:
np.random.rand(25)

array([0.98694214, 0.39464678, 0.48216736, 0.33734341, 0.3484346 ,
       0.64875533, 0.80078876, 0.1066392 , 0.32855458, 0.45652657,
       0.24126114, 0.84848998, 0.17418384, 0.28557254, 0.47500728,
       0.79485736, 0.70128925, 0.29098484, 0.10975343, 0.61100192,
       0.81942454, 0.95028218, 0.93218076, 0.98799896, 0.49908051])

Создайте следующую матрицу используя функции библиотеки NumPy:
[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ] [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ] [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ] [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ] [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ] [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ] [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ] [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ] [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ] [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1. ]

In [ ]:
mat=np.arange(0.01,1.01,0.01).reshape(10,10)
print(mat)


[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


Дана стартовая матрица (обязательно запустите код ниже в вашем решении!). Эта матрица будет использоваться в последующих задачах # это наша стартовая матрица mat = np.arange(1,26).reshape(5,5)

In [ ]:
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


Необходимо написать код который вернет следующую матрицу из стартовой:

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

Написать код обращения к элементу который вернет значение 20 из стартовой матрицы задачи

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat[3:4,4::]

array([[20]])

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

Написать код к стартовой матрице задачи l , который воспроизводит вывод, показанный ниже

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat[3:5,::]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Написать код к стартовой матрице задачи l , который воспроизводит вывод, показанный ниже

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat[4::]

array([[21, 22, 23, 24, 25]])

Написать код к стартовой матрице задачи l , который воспроизводит вывод, показанный ниже

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat[:4,::]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

Получить сумму всех значений в стартовой матрице mat  Получить стандартное отклонение в стартовой матрице mat  Получить сумму значений в колонках в стартовой матрице mat 

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat.sum()


325

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat.std()

7.211102550927978

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat.sum(axis=1)

array([ 15,  40,  65,  90, 115])